spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka1.hdp.mobike.cn,kafka2.hdp.mobike.cn,kafka3.hdp.mobike.cn,kafka4.hdp.mobike.cn,kafka5.hdp.mobike.cn,kafka6.hdp.mobike.cn,kafka7.hdp.mobike.cn,kafka8.hdp.mobike.cn,kafka9.hdp.mobike.cn,kafka10.hdp.mobike.cn
          zkNodes: zk1.hdp.mobike.cn,zk2.hdp.mobike.cn,zk3.hdp.mobike.cn,zk4.hdp.mobike.cn,zk5.hdp.mobike.cn
  sleuth:
    sampler:
      percentage: 0.01       # 1% for production

app:
  h5:
    domain-name: h5.${app.domain-name}
  m:
    domain-name: m.${app.domain-name}
  api:
    domain-name: app.${app.domain-name}

codis:
  man:
    mysql:
      url: jdbc:mysql://dbproxy.service.consul:9696/mbk_codis?useUnicode=true&amp;characterEncoding=utf-8
      user: mbk_codis
      password: M5weWzP3hBFUnJ
    global:
      enabled: true
    redisweb:
      url: http://redis.mobike.io/redisadmin/sdk/config

key-center:
  host: vault.mobike.io


zookeeper:
  address: 10.50.166.2:2181,10.50.167.2:2181,10.50.168.2:2181
  host: 10.50.166.2:2181,10.50.167.2:2181,10.50.168.2:2181

rocketmq:
  host:
    10.50.166.2
  default:
    address: 10.50.166.2:9876;10.50.167.2:9876;10.50.168.2:9876

mysql:
    host: bj3-bs-dbproxy.mobike.io
    port: 9898
    username: mbk_mario_user
    password: '{cipher}067dae257833b36d96339a277f1ca43e87ff82b9fd697066b214b8fe62128981f6dde1d6f04a42a60e4fe4e4643ebd33'

redis:
  host: 10.50.168.2
  port: 6379
  password:


mongo:
  taxi:
    host: 10.50.168.2
    database: mbk_taxi
    username: mobike001
    password: m0bike123